packages:
  - apps/*
  - packages/*
  - local-config/*
  - local-config/lint/*
  - scripts/*
catalog:
  vue: ^3.4.21
  vue-i18n: ^9.1.9
  vue-tsc: ^1.0.24
  '@vue/runtime-core': ^3.4.21
  '@dcloudio/uni-app': 3.0.0-4030620241128001
  '@dcloudio/uni-app-harmony': 3.0.0-4030620241128001
  '@dcloudio/uni-app-plus': 3.0.0-4030620241128001
  '@dcloudio/uni-components': 3.0.0-4030620241128001
  '@dcloudio/uni-h5': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-alipay': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-baidu': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-jd': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-kuaishou': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-lark': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-qq': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-toutiao': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-weixin': 3.0.0-4030620241128001
  '@dcloudio/uni-mp-xhs': 3.0.0-4030620241128001
  '@dcloudio/uni-quickapp-webview': 3.0.0-4030620241128001
  '@dcloudio/uni-automator': 3.0.0-4030620241128001
  '@dcloudio/uni-cli-shared': 3.0.0-4030620241128001
  '@dcloudio/uni-stacktracey': 3.0.0-4030620241128001
  '@dcloudio/vite-plugin-uni': 3.0.0-4030620241128001
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.10
  '@changesets/git': ^3.0.2
  '@clack/prompts': ^0.8.2
  cac: ^6.7.14
  husky: ^9.1.7
  is-ci: ^3.0.1
  lint-staged: ^15.2.11
  circular-dependency-scanner: ^2.3.0
  depcheck: ^1.4.7
  publint: ^0.2.12
  '@dcloudio/types': ^3.4.8
  '@uni-helper/uni-types': 1.0.0-alpha.6
  vite: ^6.0.3
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  '@stylistic/stylelint-plugin': ^3.1.1
  stylelint: ^16.11.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.10.0
  postcss: ^8.4.49
  postcss-html: ^1.7.0
  postcss-scss: ^4.0.9
  '@commitlint/cli': ^19.6.0
  '@commitlint/config-conventional': ^19.6.0
  cz-git: ^1.11.0
  czg: ^1.11.0
  commitlint-plugin-function-rules: ^4.0.1
  '@types/node': ^22.10.1
  '@types/eslint': ^9.6.1
  typescript: ^4.9.4
  '@typescript-eslint/eslint-plugin': ^8.18.0
  '@typescript-eslint/parser': ^8.18.0
  '@eslint/js': ^9.16.0
  eslint: ^9.16.0
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-n: ^17.15.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-vue: ^9.32.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-config-turbo: ^2.3.3
  eslint-plugin-command: ^0.2.6
  eslint-plugin-import-x: ^4.5.0
  jsonc-eslint-parser: ^2.4.0
  vue-eslint-parser: ^9.4.3
  '@manypkg/get-packages': ^2.2.2
  find-up: ^7.0.0
  chalk: ^5.3.0
  consola: ^3.2.3
  execa: ^9.5.2
  pkg-types: ^1.2.1
  rimraf: ^6.0.1
  globals: ^15.13.0
  unbuild: ^3.0.0-rc.11
  turbo: ^2.3.3
